// GENERATED by scripts/gen-addresses.mjs — DO NOT EDIT.
// Single source of truth: deployments/base-sepolia.json (stack of 2026-06-18).
// Regenerate after any redeploy: node scripts/gen-addresses.mjs

export const SEPOLIA_CHAIN_ID = 84532;
export const SEPOLIA_DEPLOY_BLOCK = 43011050;
// Flash is not redeployed every Beat freeze — its log scans use its own floor.
export const SEPOLIA_FLASH_DEPLOY_BLOCK = 43067963;

export const SEPOLIA_CONTRACTS = {
  maktubCore: "0x32840759630a97c97b7e3249725f5D9B57C36E23",
  recipientRegistry: "0x813d441D461F7759fC809E8796A54b7580116BcD",
  mktbToken: "0x6A0eE3d8ea89B3d2c552A389f1805f15207b0928",
  executorRewards: "0x87720eC0fcFf59991B4b6F8c2a12b87B83c365D3",
  mktbGovernance: "0x10E61B17312e601596E68Eb61d503B1C8AbFa86F",
  executionRelay: "0x4811F8ea7aC60D72bdbdD3ce8FA21Fc8cccE4218",
  recipientRegistryV2: "0x9465fF9350762b397f2b8157391F3723096f4161",
  maktubFlash: "0xCE40C940ed17533895Bd854ACe7C5724Fc4c1298",
};
